version: '3.8'

services:
        mariadb:
                image: mariadb:latest
                container_name: mariadb
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: auth_db
                        MYSQL_USER: auth_user
                        MYSQL_PASSWORD: auth_pass
                ports:
                        - "3306:3306"
                volumes:
                        - mariadb_data:/var/lib/mysql

volumes:
        mariadb_data:
