spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/auth_db
    username: auth_user
    password: auth_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
